# Site settings
title: Your awesome title
motto: Your motto
email: your-email@domain.com
description: 배워서 남주자
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog-tutor.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  blog-tutor

# Build settings
markdown: kramdown

disqus:
  shortname: blog-tutor
